version: '3'
services:
  server:
    depends_on:
      - database
    restart: on-failure
    image: node:lts-slim
    volumes:
      - ./api:/src
    working_dir: /src
    command: ['npm', 'start']
    ports:
      - 3001:3001
  client:
    image: node:lts-slim
    volumes:
      - ./client:/src
    working_dir: /src
    command: ['npm', 'start']
    ports:
      - 3000:3000
  database:
    image: mysql:5.7
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "sessions"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306
volumes:
  mysql_db:
